export interface Application {
    _id: string,
    firstName: string,
    lastName: string,
    dob: string,
    address: string,
    town: string,
    postcode: string,
    phoneNumber: string,
    altPhoneNumber?: string,
    emailAddress: string,
    gender: string,
    ethnicity: string,
    disability: string,
    disabilityDetails?: string,
    otherHealthConditions?: string,
    emergencyName: string,
    emergencyPhone: string,
    emergencyRelationship: string,
    createdAt: string,
}